### PR TITLE
Feature/new pages layout

### PR DESCRIPTION
**Pull request by corochena**
Guys, this branch includes three new pages about.html(carousel), careers.html(accordion) and resources.html (I think we could drop resources.html if we are short on time), this branch does not include last PR from @brazill91 , because I requested him a modification.

### CODE REVIEW

**Comment by Brazill-Mitchell** [comment]
@corochena I think we should focus on one PR at a time to keep things simple. We can avoid conflicts if we merge the earlier PR first, then update yours before merging.
What do you think @sarajoha ?

**Comment by corochena** [comment]
Updated! This PR has the changes done by @brazill91

**Review by sarajoha — APPROVED** [review]
Looks good Carlos! :)

**Comment by Brazill-Mitchell** [comment]
Looks good!

**Review by Brazill-Mitchell — APPROVED** [review]

**Pull request merged**
