### PR TITLE
Feature/pricing page

### PR DESCRIPTION
**Pull request by Brazill-Mitchell**
Hey guys! 
Sorry I'm behind with my PR. 
It's mostly just my work on the pricing page. I still have a lot of work to do, but just wanted to keep dev up to date!

### CODE REVIEW

**Review by sarajoha — APPROVED** [review]
Looks good! :blush:

**Comment by sarajoha** [comment]
@brazill91  I'm realizing now that it says there are conflicts between your branch and dev, in the `pricing.html` file... please check that out before merging :sweat_smile:

**Comment by Brazill-Mitchell** [comment]
I fixed it!
Thanks for noticing @sarajoha 👍

**Review by corochena — CHANGES_REQUESTED** [review]
@brazill91 there is code duplicated in the pricing.html file, from line 236 to line 257. I think you could copy and paste all the footer from index.html

**Comment by Brazill-Mitchell** [comment]
Thanks for the heads up @corochena, I've just made the changes and updated the PR

**Review by corochena — APPROVED** [review]
Nice job!

**Comment by corochena** [comment]
Merged

**Pull request merged**
