### PR TITLE
Feature/pricing page

### PR DESCRIPTION
**Pull request by Brazill-Mitchell**
Hey guys! This is what I have so far for the pricing page. I still have some styling to do for the plan descriptions and have to replace the background image.

### CODE REVIEW

**Review by corochena — APPROVED** [review]
You could try this page to add the ticks: https://emojipedia.org/heavy-check-mark/, just copy and paste!

**Comment by sarajoha** [comment]
Hi! It looks good!, just one questions, when I check the **Files changed** section it shows me that there is now an `index.html` in the src folder, can you check locally to see if maybe you made a copy of `index.html` to the src folder by accident?

**Comment by Brazill-Mitchell** [comment]
Thanks @corochena I'll try that!
@sarajoha You're right! Thanks for catching that, I've removed the misplaced file.

**Review by sarajoha — APPROVED** [review]
Perfect!

**Pull request merged**
