### PR TITLE
Feature/about page

### PR DESCRIPTION
**Pull request by Brazill-Mitchell**
Added a link to the atomist website

### CODE REVIEW

**Review by sarajoha — COMMENTED** [review]
If we're not going to delete this file afterwards, I suggest to put the link inside two divs, like:
`<div class='row'>`
`<div class='column'>`
**link**
`</div>`
`</div>`

**Review by sarajoha — APPROVED** [review]
Looks good to me

**Comment by corochena** [comment]
Checked

**Review by corochena — COMMENTED** [review]
Link is fine

**Review by corochena — COMMENTED** [review]
Link is fine

**Review by corochena — APPROVED** [review]
the link is fine

**Pull request merged**
